### PR TITLE
Video Upload Page Updates

### PR DESCRIPTION
**Pull request by jakirschner**
Updated the video upload file to be in line with MITx Online practices. The change to the documentation can be viewed on the [QA site](https://qa-mitx-documentation.readthedocs.io/en/latest/video/upload_video.html).

Most of the work was done under "[Upload a Video for an MITx Online Course](https://qa-mitx-documentation.readthedocs.io/en/latest/video/upload_video.html#upload-a-video-for-an-mitx-online-course)" 

Apologies about the million and one commits - I was getting used to how this would work, but I think I figured out a way to edit and review the site on my local computer that will prevent so many small commits in the future.

### Reviewers

Testing adding Joe as a reviewer to see what this process will be like for Shelly (she will need to be added to the team).

### CODE REVIEW

**Comment by JoeMartis** [comment]
Hi Jace, this was super easy to review. Nice job! 

The table under [7.3.1.3.1. Video Processing Statuses](https://qa-mitx-documentation.readthedocs.io/en/latest/video/upload_video.html#video-processing-statuses) is super wide in chrome, is there any way to make it fit within its parent table?

**Comment by jakirschner** [comment]
Awesome! I'm so glad it worked!

Unfortunately, tables are like that EVERYWHERE in the documentation. Shelly asked that I leave them alone for now. I should check and see if they're still terrible in the new RTD theme that edX is using...

**Review by JoeMartis — APPROVED** [review]
You rock!

**Comment by jakirschner** [comment]
Lol - funny story - I wasn't trying to resubmit this request. I was trying to see if I could add Shelly to it, which I was unable to do. Whoops.........

**Comment by JoeMartis** [comment]
@jakirschner you now have the power.

Masters-1

**Pull request merged**
